"""Export a Bazel package as a cached Eclipse project for JDTLS."""

import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
import zipfile


def bazel(workspace, *args):
    print("bzl " + " ".join(args), file=sys.stderr, flush=True)
    return subprocess.check_output(["bzl", *args], cwd=workspace, text=True).strip()


def jar_key(path):
    stem = re.sub(r"^(?:processed_|header_)", "", path.stem)
    return re.sub(r"-(?:src|sources|hjar|ijar)$", "", stem)


def classpath(records, execution_root):
    runtime = dict.fromkeys(execution_root / jar for row in records for jar in row["runtime"])
    full_jars = {(jar.parent, jar_key(jar)): jar for jar in runtime}
    libraries = dict(runtime)
    for row in records:
        for jar in row["compile"]:
            path = execution_root / jar
            libraries[full_jars.get((path.parent, jar_key(path)), path)] = None

    sources = {
        (path.parent, jar_key(path)): path
        for row in records
        for jar in row["sources"]
        if (path := execution_root / jar).is_file()
    }
    missing = [str(jar) for jar in libraries if not jar.is_file()]
    if missing:
        raise RuntimeError("Bazel classpath artifacts are missing: " + ", ".join(missing[:5]))
    return [(jar, sources.get((jar.parent, jar_key(jar)))) for jar in libraries]


def xml(path, root):
    ET.indent(root)
    ET.ElementTree(root).write(path, encoding="UTF-8", xml_declaration=True)


def export_project(module, project, records, execution_root, language_level):
    project.mkdir(parents=True, exist_ok=True)
    libraries = classpath(records, execution_root)
    description = ET.Element("projectDescription")
    ET.SubElement(description, "name").text = "bazel-" + hashlib.sha256(str(module).encode()).hexdigest()[:16]
    ET.SubElement(description, "comment").text = "Generated by Neovim; refresh with :BazelJavaSync"
    ET.SubElement(description, "projects")
    build = ET.SubElement(ET.SubElement(description, "buildSpec"), "buildCommand")
    ET.SubElement(build, "name").text = "org.eclipse.jdt.core.javabuilder"
    ET.SubElement(build, "arguments")
    ET.SubElement(ET.SubElement(description, "natures"), "nature").text = "org.eclipse.jdt.core.javanature"
    links = ET.SubElement(description, "linkedResources")
    entries = ET.Element("classpath")

    # Linked folders let JDTLS work on the original files without Eclipse metadata in the repo.
    for source in sorted(module.glob("src/*/java")):
        name = source.parent.name
        link = ET.SubElement(links, "link")
        ET.SubElement(link, "name").text = name
        ET.SubElement(link, "type").text = "2"
        ET.SubElement(link, "locationURI").text = source.as_uri()
        ET.SubElement(entries, "classpathentry", kind="src", path=name)

    generated = dict.fromkeys(execution_root / jar for row in records for jar in row["generated"])
    shutil.rmtree(project / "generated", ignore_errors=True)
    for jar in generated:
        destination = project / "generated" / hashlib.sha256(str(jar).encode()).hexdigest()[:16]
        destination.mkdir(parents=True)
        with zipfile.ZipFile(jar) as archive:
            for member in archive.infolist():
                path = destination / member.filename
                if member.filename.endswith(".java") and path.resolve().is_relative_to(destination.resolve()):
                    archive.extract(member, destination)
        ET.SubElement(entries, "classpathentry", kind="src", path=str(destination.relative_to(project)))

    ET.SubElement(entries, "classpathentry", kind="con", path=(
        "org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/"
        f"JavaSE-{language_level}"
    ))
    for jar, source in libraries:
        attrs = {"kind": "lib", "path": str(jar)}
        if source:
            attrs["sourcepath"] = str(source)
        ET.SubElement(entries, "classpathentry", **attrs)
    ET.SubElement(entries, "classpathentry", kind="output", path="bin")
    xml(project / ".classpath", entries)
    settings = project / ".settings"
    settings.mkdir(exist_ok=True)
    (settings / "org.eclipse.jdt.core.prefs").write_text(
        "eclipse.preferences.version=1\n" + "".join(
            f"org.eclipse.jdt.core.compiler.{key}={language_level}\n"
            for key in ("compliance", "source", "codegen.targetPlatform")
        )
    )
    xml(project / ".project", description)
    return len(libraries)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", type=Path, required=True)
    parser.add_argument("--module", type=Path, required=True)
    parser.add_argument("--project", type=Path, required=True)
    parser.add_argument("--language-level", default="25")
    parser.add_argument("targets", nargs="*")
    args = parser.parse_args()
    package = args.module.relative_to(args.workspace).as_posix()
    package = "" if package == "." else package
    targets = args.targets or bazel(
        args.workspace, "query", f'kind("java_(library|binary|test) rule", //{package}:all)', "--output=label"
    ).splitlines()
    if not targets:
        raise RuntimeError(f"No Java targets in //{package}:all")
    bazel(args.workspace, "build", *targets, "--remote_download_outputs=all", "--output_groups=+_source_jars")
    execution_root = Path(bazel(args.workspace, "info", "execution_root"))
    metadata = bazel(
        args.workspace, "cquery", "set(" + " ".join(targets) + ")", "--output=starlark",
        "--starlark:file=" + str(Path(__file__).with_name("java_classpath.bzl")),
    )
    records = [json.loads(line) for line in metadata.splitlines() if line.strip()]
    if not records:
        raise RuntimeError("The selected targets do not expose JavaInfo")
    count = export_project(args.module, args.project, records, execution_root, args.language_level)
    print(json.dumps({"project": str(args.project), "libraries": count, "targets": targets}))


if __name__ == "__main__":
    try:
        main()
    except (OSError, RuntimeError, subprocess.CalledProcessError, zipfile.BadZipFile) as error:
        print(str(error), file=sys.stderr)
        sys.exit(1)
